mutation generateCredentials($data: String) @context(scope: "private") {
  generateCredentials(data: $data) {
    userErrors {
      message
      code
      path
    }
    key
    secret
    status
  }
}
